# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
stripe_api_key: sk_test_51LO2JqLlz7ztenS3nnX10ME5EGHxNPjnySAKSVUDexIzwQQKGXKS0N68ou2T2FdYUORklRe92wmbqufLWL1HbOl0002tmi37B1
stripe_publishable_key: pk_test_51LO2JqLlz7ztenS3UXiMCgEibOSAW7wUFZNjrhp3n97beyLzFFzI6CIm7Xz6px7YesWPckVfBFjslqrywZuJNeMI005mUzkndP
#
production:
  stripe_api_key: sk_test_51LO2JqLlz7ztenS3nnX10ME5EGHxNPjnySAKSVUDexIzwQQKGXKS0N68ou2T2FdYUORklRe92wmbqufLWL1HbOl0002tmi37B1
  stripe_publishable_key: pk_test_51LO2JqLlz7ztenS3UXiMCgEibOSAW7wUFZNjrhp3n97beyLzFFzI6CIm7Xz6px7YesWPckVfBFjslqrywZuJNeMI005mUzkndP

