# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
stripe_api_key: sk_test_51LKpzjHh1cjrp6hKFXuRkGxSs9TjbzLfnC4U5I7d3qqPVi7RLWXsMCvhAN9OMhw62RD9YI6dbCdAbSVDdf7Ur0Q800BWEUoCTY
stripe_publishable_key: pk_test_51LKpzjHh1cjrp6hKnxLHXiiTR9se0txUeL2kfjwGkE7zMcyZ9lHpeIBqx7D1mtZrYI8ixlhJfRZitZ36wBqXZPa900E5HnTw6U
#
production:
  stripe_api_key: sk_test_51LKpzjHh1cjrp6hKFXuRkGxSs9TjbzLfnC4U5I7d3qqPVi7RLWXsMCvhAN9OMhw62RD9YI6dbCdAbSVDdf7Ur0Q800BWEUoCTY
  stripe_publishable_key: pk_test_51LKpzjHh1cjrp6hKnxLHXiiTR9se0txUeL2kfjwGkE7zMcyZ9lHpeIBqx7D1mtZrYI8ixlhJfRZitZ36wBqXZPa900E5HnTw6U
